# Generated by Django 4.0.5 on 2022-06-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0037_itemstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstore',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sp.studenteconomy'),
        ),
    ]
