# Generated by Django 4.0.5 on 2022-06-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0043_debriefingsession_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenteconomy',
            old_name='money',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='studenteconomy',
            old_name='money_currency',
            new_name='balance_currency',
        ),
    ]
