# Generated by Django 4.0.5 on 2022-06-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0044_rename_money_studenteconomy_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitie',
            name='student',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
