# Generated by Django 4.0.5 on 2022-06-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0045_opportunitie_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserule',
            name='student',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
