# Generated by Django 4.0.5 on 2022-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0047_alter_studenteconomy_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteconomy',
            name='jobs',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
    ]
