# Generated by Django 4.0.5 on 2022-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0048_alter_studenteconomy_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteconomy',
            name='jobs',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studenteconomy',
            name='purchased',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
