# Generated by Django 4.0.5 on 2022-06-17 17:10

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0052_alter_bill_value_alter_bill_value_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=djmoney.models.fields.MoneyField(choices=[(djmoney.money.Money(10, 'PHP'), djmoney.money.Money(10, 'PHP')), (djmoney.money.Money(20, 'PHP'), djmoney.money.Money(20, 'PHP')), (djmoney.money.Money(50, 'PHP'), djmoney.money.Money(50, 'PHP')), (djmoney.money.Money(100, 'PHP'), djmoney.money.Money(100, 'PHP'))], decimal_places=2, default=Decimal('0'), default_currency='PHP', max_digits=11),
        ),
    ]
