# Generated by Django 4.0.5 on 2022-06-17 17:22

from django.db import migrations, models
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0053_alter_bill_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='value_currency',
        ),
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=models.CharField(choices=[(1, djmoney.money.Money(10, 'PHP')), (2, djmoney.money.Money(20, 'PHP')), (3, djmoney.money.Money(50, 'PHP')), (4, djmoney.money.Money(100, 'PHP'))], default=1, max_length=200, null=True),
        ),
    ]
