# Generated by Django 4.0.5 on 2022-06-17 18:12

from django.db import migrations, models
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0054_remove_bill_value_currency_alter_bill_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='value',
            field=models.CharField(choices=[('10', djmoney.money.Money(10, 'PHP')), ('20', djmoney.money.Money(20, 'PHP')), ('50', djmoney.money.Money(50, 'PHP')), ('100', djmoney.money.Money(100, 'PHP'))], default=10, max_length=200, null=True),
        ),
    ]
