# Generated by Django 4.0.5 on 2022-06-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0057_houserule_fine_before_houserule_fine_before_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='student_assigned',
        ),
        migrations.AddField(
            model_name='job',
            name='student_assigned',
            field=models.ManyToManyField(to='sp.studenteconomy'),
        ),
    ]
