# Generated by Django 4.0.5 on 2022-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0060_opportunitie_amount_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstore',
            name='student',
        ),
        migrations.AddField(
            model_name='itemstore',
            name='student',
            field=models.ManyToManyField(to='sp.studenteconomy'),
        ),
    ]
